[package]
name = "drand_core"
description = "A drand client library."
version = "0.0.6"
authors = ["Thibault Meunier <crates@thibault.uk>"]
edition = "2021"
readme = "./README.md"
homepage = "https://github.com/thibmeu/drand-rs/tree/main/drand_core"
repository = "https://github.com/thibmeu/drand-rs"
keywords = ["drand", "rng", "random"]
categories = ["cryptography"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
ark-bls12-381 = "0.4.0"
ark-ec = "0.4.2"
ark-ff = "0.4.2"
ark-serialize = "0.4.2"
async-trait = "0.1.66"
hex = { version = "0.4.3", features = ["serde"] }
rand = "0.8.5"
reqwest = { version = "0.11.14", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1.0.155", features = ["derive", "rc"] }
serde_json = "1.0.94"
sha2 = "0.10.6"

[target.'cfg(wasm32)'.dependencies]
getrandom = { version = "0.2.8", features = ["js"] }

[dev-dependencies]
hex-literal = "0.3.4"
mockito = "0.32.5"
tokio = { version = "1.26.0", features = ["full"] }

